<?php

/**
 * Baseauthor
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $lastname
 * @property Doctrine_Collection $book
 * 
 * @method string              getName()     Returns the current record's "name" value
 * @method string              getLastname() Returns the current record's "lastname" value
 * @method Doctrine_Collection getBook()     Returns the current record's "book" collection
 * @method author              setName()     Sets the current record's "name" value
 * @method author              setLastname() Sets the current record's "lastname" value
 * @method author              setBook()     Sets the current record's "book" collection
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Baseauthor extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('author');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('lastname', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('book', array(
             'refClass' => 'bookAuthor',
             'local' => 'author_id',
             'foreign' => 'book_id'));
    }
}