<?php

/**
 * Baseregion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property Doctrine_Collection $profile
 * 
 * @method string              getName()    Returns the current record's "name" value
 * @method Doctrine_Collection getProfile() Returns the current record's "profile" collection
 * @method region              setName()    Sets the current record's "name" value
 * @method region              setProfile() Sets the current record's "profile" collection
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Baseregion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('region');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('profile', array(
             'local' => 'id',
             'foreign' => 'region_id'));
    }
}