<?php

/**
 * Baseprofile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $phone
 * @property enum $gender
 * @property string $address
 * @property integer $region_id
 * @property integer $user_id
 * @property sfGuardUser $User
 * @property region $Region
 * 
 * @method string      getPhone()     Returns the current record's "phone" value
 * @method enum        getGender()    Returns the current record's "gender" value
 * @method string      getAddress()   Returns the current record's "address" value
 * @method integer     getRegionId()  Returns the current record's "region_id" value
 * @method integer     getUserId()    Returns the current record's "user_id" value
 * @method sfGuardUser getUser()      Returns the current record's "User" value
 * @method region      getRegion()    Returns the current record's "Region" value
 * @method profile     setPhone()     Sets the current record's "phone" value
 * @method profile     setGender()    Sets the current record's "gender" value
 * @method profile     setAddress()   Sets the current record's "address" value
 * @method profile     setRegionId()  Sets the current record's "region_id" value
 * @method profile     setUserId()    Sets the current record's "user_id" value
 * @method profile     setUser()      Sets the current record's "User" value
 * @method profile     setRegion()    Sets the current record's "Region" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Baseprofile extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('profile');
        $this->hasColumn('phone', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('gender', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'male',
              1 => 'female',
             ),
             'default' => 'male',
             'notnull' => true,
             ));
        $this->hasColumn('address', 'string', 40, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 40,
             ));
        $this->hasColumn('region_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $this->hasOne('region as Region', array(
             'local' => 'region_id',
             'foreign' => 'id'));
    }
}