<?php

/**
 * Basecomment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property clob $content
 * @property integer $book
 * @property integer $user
 * @property integer $grade
 * @property book $Book
 * @property sfGuardUser $User
 * 
 * @method string      getTitle()   Returns the current record's "title" value
 * @method clob        getContent() Returns the current record's "content" value
 * @method integer     getBook()    Returns the current record's "book" value
 * @method integer     getUser()    Returns the current record's "user" value
 * @method integer     getGrade()   Returns the current record's "grade" value
 * @method book        getBook()    Returns the current record's "Book" value
 * @method sfGuardUser getUser()    Returns the current record's "User" value
 * @method comment     setTitle()   Sets the current record's "title" value
 * @method comment     setContent() Sets the current record's "content" value
 * @method comment     setBook()    Sets the current record's "book" value
 * @method comment     setUser()    Sets the current record's "user" value
 * @method comment     setGrade()   Sets the current record's "grade" value
 * @method comment     setBook()    Sets the current record's "Book" value
 * @method comment     setUser()    Sets the current record's "User" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basecomment extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('comment');
        $this->hasColumn('title', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('content', 'clob', null, array(
             'type' => 'clob',
             'notnull' => true,
             ));
        $this->hasColumn('book', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('user', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('grade', 'integer', 1, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 1,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('book as Book', array(
             'local' => 'book',
             'foreign' => 'id'));

        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user',
             'foreign' => 'id'));
    }
}