<?php

/**
 * Basecategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property Doctrine_Collection $book
 * 
 * @method string              getName() Returns the current record's "name" value
 * @method Doctrine_Collection getBook() Returns the current record's "book" collection
 * @method category            setName() Sets the current record's "name" value
 * @method category            setBook() Sets the current record's "book" collection
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basecategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('category');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'unique' => true,
             'notnull' => true,
             'length' => 255,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('book', array(
             'refClass' => 'bookCategory',
             'local' => 'category_id',
             'foreign' => 'book_id'));
    }
}