<?php

/**
 * BasebookCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $book_id
 * @property integer $category_id
 * 
 * @method integer      getBookId()      Returns the current record's "book_id" value
 * @method integer      getCategoryId()  Returns the current record's "category_id" value
 * @method bookCategory setBookId()      Sets the current record's "book_id" value
 * @method bookCategory setCategoryId()  Sets the current record's "category_id" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasebookCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('book_category');
        $this->hasColumn('book_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('category_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}