<?php

/**
 * authorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class authorTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object authorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('author');
    }
}