<?php

/**
 * bookTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class bookTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object bookTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('book');
    }
}