<?php

/**
 * bookAuthorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class bookAuthorTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object bookAuthorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('bookAuthor');
    }
}