<?php

/**
 * bookCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class bookCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object bookCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('bookCategory');
    }
}