<?php

/**
 * profileTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class profileTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object profileTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('profile');
    }
}