# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html
    Cache-control: public, max-age=120

  metas:
    title:        Elektroniczna księgarnia BOOczeK
    

  stylesheets:    [bootstrap.css, bootstrap-responsive.css, main.css]

  javascripts:    [http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js, bootstrap.js, http://ajax.aspnetcdn.com/ajax/jquery.validate/1.9/jquery.validate.js, http://ajax.microsoft.com/ajax/jquery.templates/beta1/jquery.tmpl.min.js]

  has_layout:     true
  layout:         layout