<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addprofile extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('profile', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'autoincrement' => true,
              'primary' => true,
             ),
             'phone' => 
             array(
              'type' => 'string',
              'length' => 20,
             ),
             'gender' => 
             array(
              'type' => 'enum',
              'values' => 
              array(
              0 => 'male',
              1 => 'female',
              ),
              'default' => 'male',
              'notnull' => true,
              'length' => NULL,
             ),
             'address' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 40,
             ),
             'region_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'user_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('profile');
    }
}